/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domainmodels.HoaDon;
import domainmodels.HoaDonChiTiet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.IQuanLyChiTietSanPhamService;
import services.IQuanLyHoaDonChiTietService;
import services.IQuanLyHoaDonService;
import services.impl.QuanLyChiTietSanPhamServiceImpl;
import services.impl.QuanLyHoaDonChiTietServiceImpl;
import services.impl.QuanLyHoaDonServiceImpl;
import utilities.XDate;
import viewmodels.ChiTietSanPhamViewModel;
import viewmodels.GioHangViewModel;
import viewmodels.HoaDonViewModel;
import viewmodels.SanPhamViewModel;

/**
 *
 * @author Bânbân
 */
public class QuanLyBanHangJFrame extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private DefaultTableModel dtmGH;
    private DefaultTableModel dtmHD;
    private List<ChiTietSanPhamViewModel> listSP;
    private List<HoaDonChiTiet> listGH;
    private List<GioHangViewModel> listGHView;
    private List<HoaDonViewModel> listViewHD;
    private IQuanLyChiTietSanPhamService iQuanLyChiTietSanPhamService;
    private IQuanLyHoaDonService iQuanLyHoaDonService;
    private IQuanLyHoaDonChiTietService iQuanLyHoaDonChiTietService;

    /**
     * Creates new form QuanLyBanHangJFrame
     */
    public QuanLyBanHangJFrame() {
        initComponents();
        dtm = new DefaultTableModel();
        dtmGH = new DefaultTableModel();
        dtmHD = new DefaultTableModel();
        iQuanLyChiTietSanPhamService = new QuanLyChiTietSanPhamServiceImpl();
        iQuanLyHoaDonService = new QuanLyHoaDonServiceImpl();
        iQuanLyHoaDonChiTietService = new QuanLyHoaDonChiTietServiceImpl();
        listSP = iQuanLyChiTietSanPhamService.DanhSachSP();
        listGH = new ArrayList<>();
        listGHView = new ArrayList<>();
        listViewHD = iQuanLyHoaDonService.getViewHoaDon();
        dtm = (DefaultTableModel) this.tblListSP.getModel();
        dtmGH = (DefaultTableModel) this.tblListGH.getModel();
        dtmHD = (DefaultTableModel) this.tblListHD.getModel();
        loadDataToTable(listSP);
        loadDataToTableHD(listViewHD);
        txtMaHD.setEnabled(false);
        txtNgayTao.setEnabled(false);

    }

    private void loadDataToTable(List<ChiTietSanPhamViewModel> list) {
        dtm.setRowCount(0);
        for (ChiTietSanPhamViewModel ctspvm : list) {
            dtm.addRow(ctspvm.toDataRow());
        }
    }

    private void loadDataToTableGH() {
        listGH = iQuanLyHoaDonChiTietService.getHDCTByMaHD(txtMaHD.getText());
        listGHView = iQuanLyHoaDonChiTietService.getHDCTView(txtMaHD.getText());
        dtmGH.setRowCount(0);
        for (GioHangViewModel ghvm : listGHView) {
            dtmGH.addRow(ghvm.toDataRow());
        }
    }

    private void loadDataToTableHD(List<HoaDonViewModel> list) {
        listViewHD = iQuanLyHoaDonService.getViewHoaDon();
        dtmHD.setRowCount(0);
        for (HoaDonViewModel hdvm : list) {
            dtmHD.addRow(hdvm.toDataRow());
        }
    }

    private void loadDataToTableHDTT() {
        int tt = 0;
        if (rdoCThanhToan.isSelected() == true) {
            tt = 0;
        } else if (rdoDThanhToan.isSelected() == true) {
            tt = 1;
        }
        listViewHD = iQuanLyHoaDonService.getViewHoaDonByTT(tt);
        dtmHD.setRowCount(0);
        for (HoaDonViewModel hdvm : listViewHD) {
            dtmHD.addRow(hdvm.toDataRow());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHTThanhToan = new javax.swing.ButtonGroup();
        rdoCThanhToan = new javax.swing.JRadioButton();
        rdoTatCa = new javax.swing.JRadioButton();
        rdoDaHuy = new javax.swing.JRadioButton();
        rdoDThanhToan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListHD = new javax.swing.JTable();
        btnTao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListGH = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListSP = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTienKhachDua = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        txtTienThua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHTThanhToan.add(rdoCThanhToan);
        rdoCThanhToan.setText("Chờ thanh toán");
        rdoCThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoCThanhToanMouseClicked(evt);
            }
        });

        btnHTThanhToan.add(rdoTatCa);
        rdoTatCa.setSelected(true);
        rdoTatCa.setText("Tất cả");
        rdoTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoTatCaMouseClicked(evt);
            }
        });

        btnHTThanhToan.add(rdoDaHuy);
        rdoDaHuy.setText("Đã hủy");

        btnHTThanhToan.add(rdoDThanhToan);
        rdoDThanhToan.setText("Đã thanh toán");
        rdoDThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoDThanhToanMouseClicked(evt);
            }
        });

        tblListHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã HD", "Ngày tạo", "Tên NV", "Tình trạng"
            }
        ));
        tblListHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListHD);

        btnTao.setText("Tạo hóa đơn");
        btnTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblListGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblListGH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListGHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListGH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblListSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Năm BH", "Mô tả", "SL SP", "Giá nhập", "Giá bán"
            }
        ));
        tblListSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblListSP);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("MãHD");

        jLabel2.setText("Ngày tạo");

        jLabel3.setText("TênNV");

        lblTongTien.setText("Tổng tiền");

        lblTienKhachDua.setText("Tiền khách đưa");

        jLabel4.setText("Tiền thừa");

        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtTienThua)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnThanhToan)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienKhachDua)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnThanhToan)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTao)
                                .addGap(93, 93, 93)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(rdoCThanhToan)
                .addGap(27, 27, 27)
                .addComponent(rdoTatCa)
                .addGap(18, 18, 18)
                .addComponent(rdoDaHuy)
                .addGap(18, 18, 18)
                .addComponent(rdoDThanhToan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCThanhToan)
                    .addComponent(rdoTatCa)
                    .addComponent(rdoDaHuy)
                    .addComponent(rdoDThanhToan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTao))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListHDMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblListHD.getSelectedRow();
        HoaDon h = iQuanLyHoaDonService.getHDByMa(tblListHD.getValueAt(rowIndex, 1).toString());
        showHD(h);
        listGH = iQuanLyHoaDonChiTietService.getHDCTByMaHD(txtMaHD.getText());
        listSP = iQuanLyChiTietSanPhamService.DanhSachSP();
        txtTongTien.setText(String.valueOf(getThanhTien()));
        if (h.getTinhTrang() == 1) {
            tblListSP.setEnabled(false);
            loadDataToTable(listSP);
            tblListGH.setEnabled(false);
            btnThanhToan.setEnabled(false);
        } else {
            tblListSP.setEnabled(true);
            tblListGH.setEnabled(true);
            btnThanhToan.setEnabled(true);
        }
    }//GEN-LAST:event_tblListHDMouseClicked

    private void btnTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoMouseClicked
        // TODO add your handling code here:
        dtmGH.setRowCount(0);
        listViewHD = iQuanLyHoaDonService.getViewHoaDon();
        HoaDon h = getHoaDon();
        iQuanLyHoaDonService.save(h);
        loadDataToTableHD(listViewHD);
        tblListSP.setEnabled(true);
        tblListGH.setEnabled(true);
        btnThanhToan.setEnabled(true);
        HoaDon hd = iQuanLyHoaDonService.getHDByMa(listViewHD.get(0).getMaHD());
        showHD(hd);

    }//GEN-LAST:event_btnTaoMouseClicked

    private void tblListSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListSPMouseClicked
        // TODO add your handling code here
        try {
            int rowIndex = tblListSP.getSelectedRow();
            SanPhamViewModel sp = iQuanLyChiTietSanPhamService.getCTSPByid(listSP.get(rowIndex).getId());
            if (sp.getSlTon() <= 0) {
                JOptionPane.showMessageDialog(this, "Sản phẩm đã hết", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                updateSL(sp, 1);
                addGH(rowIndex);
                double tienKhachDua = Double.parseDouble(txtTienKhachDua.getText());
                double tienThua = tienKhachDua - getThanhTien();
                txtTienThua.setText(String.valueOf(tienThua));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblListSPMouseClicked

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        try {
            double khach = Double.parseDouble(txtTienKhachDua.getText());
            double tienThua = khach - getThanhTien();
            txtTienThua.setText(String.valueOf(tienThua));
        } catch (Exception e) {
        }


    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void tblListGHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListGHMouseClicked
        // TODO add your handling code here:
        try {
            int rowIndex = tblListGH.getSelectedRow();
            HoaDonChiTiet hdct = listGH.get(rowIndex);
            SanPhamViewModel sp = hdct.SPV(); // Sản phẩm view model
            updateSL(sp, -1);
            if (hdct.getSL() == 1) {
                iQuanLyHoaDonChiTietService.delete(hdct);
            } else {
                int soLuong = hdct.getSL() - 1;
                hdct.setSL(soLuong);
                double donGia = soLuong * listGHView.get(rowIndex).getDonGia();
                hdct.setDonGia(donGia);
                iQuanLyHoaDonChiTietService.updateSL(hdct);
            }
            loadDataToTableGH();
            txtTongTien.setText(getThanhTien() + "");
            //Tinh tiền thừa
            double tienKhachDua = Double.parseDouble(txtTienKhachDua.getText());
            double tienThua = tienKhachDua - getThanhTien();
            txtTienThua.setText(String.valueOf(tienThua));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblListGHMouseClicked

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        // TODO add your handling code here:
        listViewHD = iQuanLyHoaDonService.getViewHoaDon();
        thanhToan();
        loadDataToTableHD(listViewHD);
        tblListSP.setEnabled(false);
        btnThanhToan.setEnabled(false);
    }//GEN-LAST:event_btnThanhToanMouseClicked

    private void rdoTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoTatCaMouseClicked
        // TODO add your handling code here:
        if (rdoTatCa.isSelected() == true) {
            listViewHD = iQuanLyHoaDonService.getViewHoaDon();
            loadDataToTableHD(listViewHD);
        }
    }//GEN-LAST:event_rdoTatCaMouseClicked

    private void rdoCThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoCThanhToanMouseClicked
        // TODO add your handling code here:
        loadDataToTableHDTT();
    }//GEN-LAST:event_rdoCThanhToanMouseClicked

    private void rdoDThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoDThanhToanMouseClicked
        // TODO add your handling code here:
        loadDataToTableHDTT();
    }//GEN-LAST:event_rdoDThanhToanMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String keyWord = txtSearch.getText().trim();
        search(keyWord);
    }//GEN-LAST:event_txtSearchKeyReleased
    private void addGH(int index) {
        boolean check = true;
        // check xem giỏ hàng có SP chưa
        String id = listSP.get(index).getId();
        listGH = iQuanLyHoaDonChiTietService.getHDCTByMaHD(txtMaHD.getText());
        for (HoaDonChiTiet hdct : listGH) {
            if (hdct.SPV().getId().equalsIgnoreCase(id)) {
                int SL = hdct.getSL() + 1;
                hdct.setSL(SL);
                double donGia = SL * hdct.SPV().getGiaBan();
                hdct.setDonGia(donGia);
                iQuanLyHoaDonChiTietService.updateSL(hdct);
                check = false;
            }
        }
        if (check == true) {
            HoaDonChiTiet hdct = new HoaDonChiTiet(iQuanLyHoaDonService.getHDByMa(txtMaHD.getText()), iQuanLyChiTietSanPhamService.getCTSPByid(id), 1, listSP.get(index).getGiaBan());
            iQuanLyHoaDonChiTietService.addSP(hdct);
        }
        //add row tblGioHang
        loadDataToTableGH();
        //Tinh Tien
        txtTongTien.setText(String.valueOf(getThanhTien()));
    }

    public double getThanhTien() {
        double money = 0;
        for (int i = 0; i < tblListGH.getRowCount(); i++) {
            money += Double.parseDouble(tblListGH.getValueAt(i, 5) + "");
        }
        return money;
    }

    public void updateSL(SanPhamViewModel ctsp, int soLuong) {
        iQuanLyChiTietSanPhamService.updateSL(ctsp, soLuong);
        for (int i = 0; i < listSP.size() - 1; i++) {
            if (listSP.get(i).getId().endsWith(ctsp.getId())) {
                tblListSP.setValueAt(ctsp.getSlTon() - soLuong, i, 5);
            }
        }
    }

    public void showHD(HoaDon h) {
        txtMaHD.setText(h.getMa());
        txtNgayTao.setText(XDate.toString(h.getNgayTao()));
        txtTienThua.setText(String.valueOf(getThanhTien()));
        txtTienKhachDua.setText("");
        txtTienThua.setText("");
        loadDataToTableGH();
    }

    public HoaDon getHoaDon() {
        int dem = Integer.parseInt(listViewHD.get(0).getMaHD().substring(2, listViewHD.get(0).getMaHD().length())) + 1;
        String ma = "HĐ" + dem;
        return new HoaDon(ma, XDate.now(), 1);
    }

    public void thanhToan() {
        HoaDon h = iQuanLyHoaDonService.getHDByMa(txtMaHD.getText());
        iQuanLyHoaDonService.thanhToan(h);
    }

    public void search(String keyWord) {
        listSP = iQuanLyChiTietSanPhamService.search(keyWord);
        dtm.setRowCount(0);
        for (ChiTietSanPhamViewModel ctsp : listSP) {
            dtm.addRow(ctsp.toDataRow());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyBanHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnHTThanhToan;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTienKhachDua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JRadioButton rdoCThanhToan;
    private javax.swing.JRadioButton rdoDThanhToan;
    private javax.swing.JRadioButton rdoDaHuy;
    private javax.swing.JRadioButton rdoTatCa;
    private javax.swing.JTable tblListGH;
    private javax.swing.JTable tblListHD;
    private javax.swing.JTable tblListSP;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
